### PR TITLE
Fix votes alert

### LINKED ISSUE #110: Fix answer min / max alerts
Rather than setting the text dynamically, I highly suggest to use `View#setVisiblity(...)` with the constants `HIDDEN` and `VISIBLE`. On top of that, if you add the `animateLayoutChanges` to the XML layout that contains the view, some default animations will be provided "for free".

### PR DESCRIPTION
**Pull request by glsubri**
Fix #110

### CODE REVIEW

File: app/src/main/java/ch/heigvd/pro/b04/android/question/QuestionViewModel.kt [hunk 1]
```diff
@@ -109,38 +112,45 @@ class QuestionViewModel(application: Application, question : Question, private v
...
             // Note that for now, we do not take the result into account
             viewModelScope.launch {
                 voteForAnswerSuspending(answer, token)
             }
+        } else if (max != 0 && max == nbCheckedAnswer.value) {
+            notifyMaxAnswer.value = question.answerMax
+
+            // Not useless: if we do not set the value back to 0, the activity will not be
+            // notified if the user clicks multiple times on an answer
+            notifyMaxAnswer.value = 0
```
Comment (glsubri) [inline app/src/main/java/ch/heigvd/pro/b04/android/question/QuestionViewModel.kt:132]: If someone knows how to do this more cleanly, please let me know

**Review by alexandrepiveteau — APPROVED** [review]
